services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    runtime: nvidia
    ports:
      - "7000:7000"
    env_file:
      - .env
    volumes:
      - ./ssl:/ssl
      - .:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    # Параметры для лучшей производительности
    ipc: host
    ulimits:
      memlock:
        soft: -1
        hard: -1
      stack:
        soft: 67108864
        hard: 67108864
    restart: unless-stopped